//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NongSan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class About
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Content { get; set; }
        public string Avartar { get; set; }
        public string Type { get; set; }
        public string Image1 { get; set; }
        public string Image2 { get; set; }
        public string Content1 { get; set; }
        public string Content2 { get; set; }
    }
}
