//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NongSan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        public int Id { get; set; }
        public string Slug { get; set; }
        public string CategoryName { get; set; }
        public string MetaTitle { get; set; }
        public string MetaDescription { get; set; }
        public string MetaKeyword { get; set; }
        public Nullable<int> Ord { get; set; }
        public string Avartar { get; set; }
        public string Description { get; set; }
        public Nullable<int> ParrentID { get; set; }
        public bool IsHome { get; set; }
        public string Url { get; set; }
    }
}
