//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NongSan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class New
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Content { get; set; }
        public Nullable<System.DateTime> DatePost { get; set; }
        public string Thumbnail { get; set; }
        public string ShortDescription { get; set; }
        public string Slug { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public Nullable<int> CategoryNewId { get; set; }
        public string PixelFacebook { get; set; }
    }
}
