//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NongSan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int ID { get; set; }
        public string FullName { get; set; }
        public string Address { get; set; }
        public string Email { get; set; }
        public string PhoneNumber { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
        public string Note { get; set; }
        public string SearchText { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public Nullable<int> StatusID { get; set; }
        public string OD_ID { get; set; }
        public string CreateBy { get; set; }
    }
}
