//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NongSan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int Id { get; set; }
        public string Slug { get; set; }
        public string ProductName { get; set; }
        public string Content { get; set; }
        public decimal Price { get; set; }
        public string Image { get; set; }
        public int CategoryId { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
        public string MetaKeyWord { get; set; }
        public string MetaDescription { get; set; }
        public string ShortDescription { get; set; }
        public string MetaTitle { get; set; }
        public string Type { get; set; }
        public string Images1 { get; set; }
        public string Images2 { get; set; }
        public string Images3 { get; set; }
        public string Images4 { get; set; }
        public string Images5 { get; set; }
        public string Images6 { get; set; }
        public bool IsHome { get; set; }
        public string Promotion1 { get; set; }
        public string Promotion2 { get; set; }
        public string Promotion3 { get; set; }
        public string Promotion4 { get; set; }
        public string Promotion5 { get; set; }
        public string Promotion6 { get; set; }
        public string Promotion7 { get; set; }
        public string PixelFacebook { get; set; }
    }
}
