//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NongSan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Setting
    {
        public int ID { get; set; }
        public string Logo { get; set; }
        public string MetaKeyWord { get; set; }
        public string MetaDescription { get; set; }
        public string MetaTitle { get; set; }
        public string Email { get; set; }
        public string PhoneNumber { get; set; }
        public string Address { get; set; }
        public string Sologan { get; set; }
        public string Favicon { get; set; }
        public string Meta1 { get; set; }
        public string Meta2 { get; set; }
        public string Meta3 { get; set; }
        public string PixelFacebook { get; set; }
        public string ImageBgProduct { get; set; }
        public string DescriptionProduct { get; set; }
        public string ImageBgCommnet { get; set; }
        public string DescriptionNew { get; set; }
        public string DesciptionTop { get; set; }
        public string ImageBgNew { get; set; }
    }
}
